
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action closeAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action deleteAction;
	private global::Gtk.VBox vboxMain_MW;
	private global::Gtk.VBox vboxLogin;
	private global::Gtk.HBox hboxUser;
	private global::Gtk.Label labelUser;
	private global::Gtk.Entry entryUser;
	private global::Gtk.HBox hboxPwd;
	private global::Gtk.Label labelPwd;
	private global::Gtk.Entry entryPwd;
	private global::Gtk.Button buttonLogin;
	private global::Gtk.VBox vboxTable;
	private global::Gtk.HBox hboxTableTB;
	private global::Gtk.Toolbar tableTB1;
	private global::Gtk.Toolbar tableTB2;
	private global::Gtk.Toolbar tableTB3;
	private global::Gtk.ScrolledWindow GtkSWTable;
	private global::Gtk.TreeView treeView;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.refreshAction = new global::Gtk.Action ("refreshAction", global::Mono.Unix.Catalog.GetString ("Actualizar"), null, "gtk-refresh");
		this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Actualizar");
		w1.Add (this.refreshAction, null);
		this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Vaciar"), null, "gtk-close");
		this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Vaciar");
		w1.Add (this.closeAction, null);
		this.editAction = new global::Gtk.Action ("editAction", global::Mono.Unix.Catalog.GetString ("Editar"), null, "gtk-edit");
		this.editAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.editAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("Eliminar"), null, "gtk-delete");
		this.deleteAction.Sensitive = false;
		this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Eliminar");
		w1.Add (this.deleteAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Acceso a Datos");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_task", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.DefaultWidth = 300;
		this.DefaultHeight = 75;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain_MW = new global::Gtk.VBox ();
		this.vboxMain_MW.Name = "vboxMain_MW";
		this.vboxMain_MW.Spacing = 6;
		// Container child vboxMain_MW.Gtk.Box+BoxChild
		this.vboxLogin = new global::Gtk.VBox ();
		this.vboxLogin.Name = "vboxLogin";
		this.vboxLogin.Spacing = 6;
		// Container child vboxLogin.Gtk.Box+BoxChild
		this.hboxUser = new global::Gtk.HBox ();
		this.hboxUser.Name = "hboxUser";
		this.hboxUser.Spacing = 6;
		// Container child hboxUser.Gtk.Box+BoxChild
		this.labelUser = new global::Gtk.Label ();
		this.labelUser.Name = "labelUser";
		this.labelUser.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario");
		this.hboxUser.Add (this.labelUser);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxUser [this.labelUser]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hboxUser.Gtk.Box+BoxChild
		this.entryUser = new global::Gtk.Entry ();
		this.entryUser.CanFocus = true;
		this.entryUser.Name = "entryUser";
		this.entryUser.IsEditable = true;
		this.entryUser.InvisibleChar = '•';
		this.hboxUser.Add (this.entryUser);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxUser [this.entryUser]));
		w3.Position = 1;
		this.vboxLogin.Add (this.hboxUser);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxLogin [this.hboxUser]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vboxLogin.Gtk.Box+BoxChild
		this.hboxPwd = new global::Gtk.HBox ();
		this.hboxPwd.Name = "hboxPwd";
		this.hboxPwd.Spacing = 6;
		// Container child hboxPwd.Gtk.Box+BoxChild
		this.labelPwd = new global::Gtk.Label ();
		this.labelPwd.Name = "labelPwd";
		this.labelPwd.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña");
		this.hboxPwd.Add (this.labelPwd);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hboxPwd [this.labelPwd]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hboxPwd.Gtk.Box+BoxChild
		this.entryPwd = new global::Gtk.Entry ();
		this.entryPwd.CanFocus = true;
		this.entryPwd.Name = "entryPwd";
		this.entryPwd.IsEditable = true;
		this.entryPwd.InvisibleChar = '•';
		this.hboxPwd.Add (this.entryPwd);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxPwd [this.entryPwd]));
		w6.Position = 1;
		this.vboxLogin.Add (this.hboxPwd);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxLogin [this.hboxPwd]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vboxLogin.Gtk.Box+BoxChild
		this.buttonLogin = new global::Gtk.Button ();
		this.buttonLogin.CanFocus = true;
		this.buttonLogin.Name = "buttonLogin";
		this.buttonLogin.UseUnderline = true;
		this.buttonLogin.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.vboxLogin.Add (this.buttonLogin);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxLogin [this.buttonLogin]));
		w8.Position = 2;
		this.vboxMain_MW.Add (this.vboxLogin);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxMain_MW [this.vboxLogin]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vboxMain_MW.Gtk.Box+BoxChild
		this.vboxTable = new global::Gtk.VBox ();
		this.vboxTable.Name = "vboxTable";
		this.vboxTable.Spacing = 6;
		// Container child vboxTable.Gtk.Box+BoxChild
		this.hboxTableTB = new global::Gtk.HBox ();
		this.hboxTableTB.Name = "hboxTableTB";
		this.hboxTableTB.Spacing = 6;
		// Container child hboxTableTB.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='tableTB1'><toolitem name='editAction' action='editAction'/></toolbar></ui>");
		this.tableTB1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tableTB1")));
		this.tableTB1.Name = "tableTB1";
		this.tableTB1.ShowArrow = false;
		this.hboxTableTB.Add (this.tableTB1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxTableTB [this.tableTB1]));
		w10.Position = 0;
		// Container child hboxTableTB.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='tableTB2'><toolitem name='deleteAction' action='deleteAction'/></toolbar></ui>");
		this.tableTB2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tableTB2")));
		this.tableTB2.Name = "tableTB2";
		this.tableTB2.ShowArrow = false;
		this.hboxTableTB.Add (this.tableTB2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxTableTB [this.tableTB2]));
		w11.Position = 1;
		// Container child hboxTableTB.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='tableTB3'><toolitem name='refreshAction' action='refreshAction'/><separator/><toolitem name='closeAction' action='closeAction'/></toolbar></ui>");
		this.tableTB3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tableTB3")));
		this.tableTB3.Name = "tableTB3";
		this.tableTB3.ShowArrow = false;
		this.hboxTableTB.Add (this.tableTB3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxTableTB [this.tableTB3]));
		w12.Position = 2;
		w12.Expand = false;
		this.vboxTable.Add (this.hboxTableTB);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxTable [this.hboxTableTB]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vboxTable.Gtk.Box+BoxChild
		this.GtkSWTable = new global::Gtk.ScrolledWindow ();
		this.GtkSWTable.Name = "GtkSWTable";
		this.GtkSWTable.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkSWTable.Gtk.Container+ContainerChild
		this.treeView = new global::Gtk.TreeView ();
		this.treeView.CanFocus = true;
		this.treeView.Name = "treeView";
		this.GtkSWTable.Add (this.treeView);
		this.vboxTable.Add (this.GtkSWTable);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxTable [this.GtkSWTable]));
		w15.Position = 1;
		this.vboxMain_MW.Add (this.vboxTable);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxMain_MW [this.vboxTable]));
		w16.Position = 1;
		this.Add (this.vboxMain_MW);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.vboxTable.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.editAction.Activated += new global::System.EventHandler (this.OnEditActionActivated);
		this.deleteAction.Activated += new global::System.EventHandler (this.OnDeleteActionActivated);
		this.buttonLogin.Clicked += new global::System.EventHandler (this.OnButtonLoginClicked);
	}
}
