
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class EditWindow
	{
		private global::Gtk.VBox editVBox;
		private global::Gtk.HBox btnHBox;
		private global::Gtk.Button btnInsert;
		private global::Gtk.Button btnUpdate;
		private global::Gtk.Button btnDelete;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textView;
		private global::Gtk.Button btnExecute;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticulo.EditWindow
			this.Name = "PArticulo.EditWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Editar");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 500;
			this.DefaultHeight = 250;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child PArticulo.EditWindow.Gtk.Container+ContainerChild
			this.editVBox = new global::Gtk.VBox ();
			this.editVBox.Name = "editVBox";
			this.editVBox.Spacing = 6;
			// Container child editVBox.Gtk.Box+BoxChild
			this.btnHBox = new global::Gtk.HBox ();
			this.btnHBox.Name = "btnHBox";
			this.btnHBox.Spacing = 6;
			// Container child btnHBox.Gtk.Box+BoxChild
			this.btnInsert = new global::Gtk.Button ();
			this.btnInsert.CanFocus = true;
			this.btnInsert.Name = "btnInsert";
			this.btnInsert.UseUnderline = true;
			this.btnInsert.Label = global::Mono.Unix.Catalog.GetString ("INSERT");
			this.btnHBox.Add (this.btnInsert);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.btnHBox [this.btnInsert]));
			w1.Position = 0;
			// Container child btnHBox.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("UPDATE");
			this.btnHBox.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.btnHBox [this.btnUpdate]));
			w2.Position = 1;
			// Container child btnHBox.Gtk.Box+BoxChild
			this.btnDelete = new global::Gtk.Button ();
			this.btnDelete.CanFocus = true;
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.UseUnderline = true;
			this.btnDelete.Label = global::Mono.Unix.Catalog.GetString ("DELETE");
			this.btnHBox.Add (this.btnDelete);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.btnHBox [this.btnDelete]));
			w3.Position = 2;
			this.editVBox.Add (this.btnHBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.editVBox [this.btnHBox]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child editVBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textView = new global::Gtk.TextView ();
			this.textView.CanFocus = true;
			this.textView.Name = "textView";
			this.GtkScrolledWindow.Add (this.textView);
			this.editVBox.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.editVBox [this.GtkScrolledWindow]));
			w6.Position = 1;
			// Container child editVBox.Gtk.Box+BoxChild
			this.btnExecute = new global::Gtk.Button ();
			this.btnExecute.CanFocus = true;
			this.btnExecute.Name = "btnExecute";
			this.btnExecute.UseUnderline = true;
			// Container child btnExecute.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("EXECUTE");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.btnExecute.Add (w7);
			this.editVBox.Add (this.btnExecute);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.editVBox [this.btnExecute]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.editVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnInsert.Clicked += new global::System.EventHandler (this.OnBtnInsertClicked);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.OnBtnUpdateClicked);
		}
	}
}
