
// This file has been generated by the GUI designer. Do not modify.
namespace PMyWidget
{
	public partial class PersonaView
	{
		private global::Gtk.Table tableMain;
		private global::Gtk.Entry entryApellido;
		private global::Gtk.Entry entryNombre;
		private global::Gtk.Label labelApellido;
		private global::Gtk.Label labelNombre;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PMyWidget.PersonaView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PMyWidget.PersonaView";
			// Container child PMyWidget.PersonaView.Gtk.Container+ContainerChild
			this.tableMain = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tableMain.Name = "tableMain";
			this.tableMain.RowSpacing = ((uint)(6));
			this.tableMain.ColumnSpacing = ((uint)(6));
			// Container child tableMain.Gtk.Table+TableChild
			this.entryApellido = new global::Gtk.Entry ();
			this.entryApellido.CanFocus = true;
			this.entryApellido.Name = "entryApellido";
			this.entryApellido.IsEditable = true;
			this.entryApellido.InvisibleChar = '•';
			this.tableMain.Add (this.entryApellido);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.tableMain [this.entryApellido]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.entryNombre = new global::Gtk.Entry ();
			this.entryNombre.CanFocus = true;
			this.entryNombre.Name = "entryNombre";
			this.entryNombre.IsEditable = true;
			this.entryNombre.InvisibleChar = '•';
			this.tableMain.Add (this.entryNombre);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableMain [this.entryNombre]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.labelApellido = new global::Gtk.Label ();
			this.labelApellido.Name = "labelApellido";
			this.labelApellido.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellidos");
			this.tableMain.Add (this.labelApellido);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableMain [this.labelApellido]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableMain.Gtk.Table+TableChild
			this.labelNombre = new global::Gtk.Label ();
			this.labelNombre.Name = "labelNombre";
			this.labelNombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.tableMain.Add (this.labelNombre);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableMain [this.labelNombre]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.tableMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
