
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vboxMain;
	private global::Gtk.Notebook notebook2;
	private global::Gtk.Label labelPage1;
	private global::Gtk.Label labelPage2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 1;
		// Notebook tab
		global::Gtk.Label w1 = new global::Gtk.Label ();
		w1.Visible = true;
		this.notebook2.Add (w1);
		this.labelPage1 = new global::Gtk.Label ();
		this.labelPage1.Name = "labelPage1";
		this.labelPage1.LabelProp = global::Mono.Unix.Catalog.GetString ("Pestaña 1");
		this.notebook2.SetTabLabel (w1, this.labelPage1);
		this.labelPage1.ShowAll ();
		// Notebook tab
		global::Gtk.Label w2 = new global::Gtk.Label ();
		w2.Visible = true;
		this.notebook2.Add (w2);
		this.labelPage2 = new global::Gtk.Label ();
		this.labelPage2.Name = "labelPage2";
		this.labelPage2.LabelProp = global::Mono.Unix.Catalog.GetString ("   +   ");
		this.notebook2.SetTabLabel (w2, this.labelPage2);
		this.labelPage2.ShowAll ();
		this.vboxMain.Add (this.notebook2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.notebook2]));
		w3.Position = 1;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
