
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action ArchivoAction;
	private global::Gtk.Action AbrirAction;
	private global::Gtk.Action CerrarAction;
	private global::Gtk.Action SalirAction;
	private global::Gtk.Action ArticuloAction;
	private global::Gtk.Action CategoriaAction;
	private global::Gtk.VBox vboxMain;
	private global::Gtk.MenuBar menuBar;
	private global::Gtk.Notebook noteBook;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Salir"), global::Mono.Unix.Catalog.GetString ("Salir"), "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salir");
		w1.Add (this.quitAction, null);
		this.ArchivoAction = new global::Gtk.Action ("ArchivoAction", global::Mono.Unix.Catalog.GetString ("Archivo"), null, null);
		this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Archivo");
		w1.Add (this.ArchivoAction, null);
		this.AbrirAction = new global::Gtk.Action ("AbrirAction", global::Mono.Unix.Catalog.GetString ("Abrir pestañas"), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Abrir");
		w1.Add (this.AbrirAction, null);
		this.CerrarAction = new global::Gtk.Action ("CerrarAction", global::Mono.Unix.Catalog.GetString ("Cerrar pestañas"), null, null);
		this.CerrarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cerrar");
		w1.Add (this.CerrarAction, null);
		this.SalirAction = new global::Gtk.Action ("SalirAction", global::Mono.Unix.Catalog.GetString ("_Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salir");
		w1.Add (this.SalirAction, null);
		this.ArticuloAction = new global::Gtk.Action ("ArticuloAction", global::Mono.Unix.Catalog.GetString ("Artículo"), null, null);
		this.ArticuloAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Articulo");
		w1.Add (this.ArticuloAction, null);
		this.CategoriaAction = new global::Gtk.Action ("CategoriaAction", global::Mono.Unix.Catalog.GetString ("Categoria"), null, null);
		this.CategoriaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Categoria");
		w1.Add (this.CategoriaAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menuBar'><menu name='ArchivoAction' action='ArchivoAction'><menu name='AbrirAction' action='AbrirAction'><menuitem name='ArticuloAction' action='ArticuloAction'/><menuitem name='CategoriaAction' action='CategoriaAction'/></menu><menuitem name='CerrarAction' action='CerrarAction'/><separator/><menuitem name='SalirAction' action='SalirAction'/></menu></menubar></ui>");
		this.menuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menuBar")));
		this.menuBar.Name = "menuBar";
		this.vboxMain.Add (this.menuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.noteBook = new global::Gtk.Notebook ();
		this.noteBook.CanFocus = true;
		this.noteBook.Name = "noteBook";
		this.noteBook.CurrentPage = -1;
		this.vboxMain.Add (this.noteBook);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.noteBook]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
